apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: main-container
          image: "public.ecr.aws/nginx/nginx:alpine"
          ports:
            - containerPort: 80
        - name: sidecar-container
          image: "public.ecr.aws/docker/library/busybox:1.36"
          command: ["tail", "-f", "/dev/null"]

